Repository ezsystems/ezplatform-ee-demo, pull requests merged in 2018-11, with the labels that each got.

#109 DEMO-239: Improve homepage design (mobile)
  web/assets/scss/_article.scss
  web/assets/scss/_landing.page.scss
Labels: Ready for review

#107 DEMO-228: Test layouts
  app/Resources/views/themes/tastefulplanet/layouts/test_layout.html.twig
  app/config/default_layouts.yml
  app/config/services.yml
  app/config/services/installer.yml
  src/AppBundle/Event/PageFieldType/Attribute/AttributeSerializationSubscriber.php
  src/AppBundle/Installer/PlatformEEDemoTestLayoutsInstaller.php
  src/AppBundle/MigrationVersions/landing_page_tests.yml
  web/assets/images/page_builder/layouts/test.png
Labels: Work in progress

#110 EZP-29171: Update Navbar menu items order
  app/config/services.yml
  src/AppBundle/Menu/ReorderMenuListener.php
Labels: QA approved, Ready for review

#117 EZP-29832: Unable to use AdminUI without admin rights
  src/AppBundle/Menu/ReorderMenuListener.php
Labels: QA approved
