Repository ezsystems/ezplatform-ee-demo, pull requests merged in 2018-12, with the labels that each got.

#118 EZEE-2305: Port PageBuilder tests to demo
  tests/AppBundle/Behat/EnterpriseDemoEnvironmentConstants.php
  tests/AppBundle/Behat/PageElement/BlockPreview/DemoBannerPreview.php
  tests/AppBundle/Behat/PageElement/BlockPreview/DemoCollectionPreview.php
  tests/AppBundle/Behat/PageElement/BlockPreview/DemoContentListPreview.php
  tests/AppBundle/Behat/PageElement/BlockPreview/DemoContentSchedulerPreview.php
  tests/AppBundle/Behat/PageElement/BlockPreview/DemoEmbedPreview.php
  tests/AppBundle/Behat/PageElement/BlockPreview/DemoGalleryPreview.php
  tests/AppBundle/Behat/PageElement/BlockPreview/DemoRSSPreview.php
  tests/AppBundle/Behat/PageElement/BlockPreview/DemoVideoPreview.php
  tests/AppBundle/Behat/PageElement/BlockPreview/HeroPreview.php
  tests/AppBundle/Behat/PageElement/Blocks/DemoBannerBlock.php
  tests/AppBundle/Behat/PageElement/Blocks/DemoCodeBlock.php
  tests/AppBundle/Behat/PageElement/Blocks/DemoCollectionBlock.php
  tests/AppBundle/Behat/PageElement/Blocks/DemoContentListBlock.php
  tests/AppBundle/Behat/PageElement/Blocks/DemoContentSchedulerBlock.php
  tests/AppBundle/Behat/PageElement/Blocks/DemoEmbedBlock.php
  tests/AppBundle/Behat/PageElement/Blocks/DemoGalleryBlock.php
  tests/AppBundle/Behat/PageElement/Blocks/DemoVideoBlock.php
  tests/AppBundle/Behat/PageElement/Blocks/HeroBlock.php
  tests/AppBundle/Behat/PageElement/DemoEnterpriseElementFactory.php
  tests/AppBundle/Behat/PageObject/DemoEnterprisePageObjectFactory.php
  tests/AppBundle/Behat/PageObject/DemoLandingPagePreview.php
  tests/AppBundle/Behat/PlatformDemoEnvironmentConstants.php
Labels: Ready for MERGE

#122 EZP-29936: Synchronize workflow database schema in installers
  src/AppBundle/MigrationVersions/schema-ee_mysql.sql
Labels: Improvement, Ready for review

#126 EZEE-2647: Move existing workflows to demo installation
  app/config/ezplatform.yml
  app/config/workflows.yml
Labels: Improvement, Ready for MERGE, Ready for review

#123 DEMO-274: New custom tags
  app/Resources/translations/custom_tags.en.yaml
  app/Resources/views/themes/tastefulplanet/fields/ezrichtext/custom_tags/call_to_action.html.twig
  app/Resources/views/themes/tastefulplanet/fields/ezrichtext/custom_tags/factbox.html.twig
  app/config/fields/ezrichtext/custom_tags.yml
  web/assets/scss/_custom.tags.scss
  web/assets/scss/demo.scss
Labels: Ready for review
