Repository ezsystems/ezplatform-ee-demo, pull requests merged in 2018-10, with the labels that each got.

#77 EZEE-2304 As a QA I want to run DBP and FXW test features on Enterprise Demo
  bin/.travis/trusty/setup_ezplatform.sh
  tests/AppBundle/Behat/EnterpriseDemoEnvironmentConstants.php
Labels: waiting for review

#95 DEMO-222: Fix issues with special character in block templates
  app/Resources/views/themes/tastefulplanet/parts/render_description.html.twig
Labels: waiting for review

#103 DEMO-233: Places Block - map update
  app/Resources/views/themes/tastefulplanet/blocks/places/map.html.twig
  app/Resources/views/themes/tastefulplanet/full/place_list.html.twig
  app/Resources/views/themes/tastefulplanet/pagelayout.html.twig
  app/Resources/views/themes/tastefulplanet/parts/map.html.twig
  web/assets/images/map_tile/2/-2/0.png
  web/assets/images/map_tile/2/-2/0@2x.png
  web/assets/images/map_tile/2/-2/1.png
  web/assets/images/map_tile/2/-2/1@2x.png
  web/assets/images/map_tile/2/-2/2.png
  web/assets/images/map_tile/2/-2/2@2x.png
  web/assets/images/map_tile/2/-2/3.png
  web/assets/images/map_tile/2/-2/3@2x.png
  web/assets/images/map_tile/2/5/0.png
  web/assets/images/map_tile/2/5/0@2x.png
  web/assets/images/map_tile/2/5/1.png
  web/assets/images/map_tile/2/5/1@2x.png
  web/assets/images/map_tile/2/5/2.png
  web/assets/images/map_tile/2/5/2@2x.png
  web/assets/images/map_tile/2/5/3.png
  web/assets/images/map_tile/2/5/3@2x.png
  web/assets/js/blocks/placesMapLoader.js
  web/assets/js/main.js
Labels: Improvement, Ready for review

#105 DEMO-235: Improve design of blocks to avoid styling issues in Page Builder
  app/Resources/views/blocks/_block.html.twig
  app/Resources/views/themes/tastefulplanet/zone/zone.html.twig
  web/assets/scss/_landing.page.scss
Labels: Improvement, Ready for QA, Ready for review

#104 DEMO-234: Improve page zones layout
  app/Resources/views/themes/tastefulplanet/layouts/1.html.twig
  app/Resources/views/themes/tastefulplanet/layouts/1_2.html.twig
  app/Resources/views/themes/tastefulplanet/layouts/1_2__1.html.twig
  app/Resources/views/themes/tastefulplanet/layouts/1w__1__1w.html.twig
  app/Resources/views/themes/tastefulplanet/layouts/1w__2_1__2_1__1w.html.twig
  app/Resources/views/themes/tastefulplanet/layouts/2_1.html.twig
  app/Resources/views/themes/tastefulplanet/layouts/2_1__1.html.twig
  app/Resources/views/themes/tastefulplanet/layouts/container.html.twig
  app/Resources/views/themes/tastefulplanet/layouts/home.html.twig
Labels: Improvement, Ready for QA, Ready for review

#108 DEMO-238: make embedded blog post more consistent
  app/Resources/views/themes/tastefulplanet/block_item/blog_post/default.html.twig
  web/assets/scss/_landing.page.scss
Labels: Ready for review
